pushed main to be able to compare
estherniyo/quizzical pull request #1
Opened 2023-03-15 14:18 UTC by estherniyo

2023-03-16 14:12 UTC, mercihabam requested changes
# Kudos for what you've accomplished

Consider applying the changes in the comments I left below to improve the code quality.

2023-03-16 14:12 UTC, mercihabam commented on src/App.jsx
> +      </svg>
It's recommended to put all SVG files in their respective files

2023-03-16 14:12 UTC, mercihabam commented on src/App.jsx
> +  const close = (e) => {
`e` as argument here is a little ambiguous. Use something like `event`

2023-03-16 14:12 UTC, mercihabam commented on src/components/Alert.jsx
> +const Alert = () => {
It's good to be consistent by either using arrow function components or function declaration components, but not both of them at the same time.

2023-03-16 14:12 UTC, mercihabam commented on src/components/Options.jsx
For good practice, a component shouldn't exceed 100 lines of code. If you find yourself having a component that has more lines than that number, meaning you should think about separating your components into two or more other components according to the usage of each block of code.

2023-03-16 14:12 UTC, mercihabam commented on src/context/AppContext.jsx
This file contains too many lines of code for a component, and it uses the arrow function components and function declaration components at the same time. Consider using one, and separating your file into many according to the content concern

2023-03-16 14:12 UTC, mercihabam commented on src/context/AppContext.jsx
> +        answers: answers.map((item) => {
While you're looping it's good to name the `item` argument properly. In this case, it could be for example `answer`.

2023-03-16 14:29 UTC, NiyonkuruEsther commented on src/App.jsx
> +  const close = (e) => {
if I use i in the map are you very certain that you don't understand index?!

2023-03-16 14:30 UTC, NiyonkuruEsther commented on src/components/Alert.jsx
> +const Alert = () => {
Where did I use both at the same time! I think by using both at the same time the codes can't run!

2023-03-16 14:30 UTC, NiyonkuruEsther commented on src/components/Options.jsx
Yes! That's a good recommendation for the next codes!

2023-03-16 14:32 UTC, NiyonkuruEsther commented on src/context/AppContext.jsx
> +        answers: answers.map((item) => {
One can't have more than one item, thus I don't see the problem if you won't confuse the item with something else because they are a lot

2023-03-16 14:52 UTC, NiyonkuruEsther commented on src/App.jsx
> +      </svg>
Sure thing

2023-03-18 16:03 UTC, NiyonkuruEsther commented on src/App.jsx
> +      </svg>
Done

2023-03-18 16:17 UTC, NiyonkuruEsther commented on src/App.jsx
> +  const close = (e) => {
done

2023-03-18 16:17 UTC, NiyonkuruEsther commented on src/components/Alert.jsx
> +const Alert = () => {
Done wit this too

2023-03-18 16:18 UTC, NiyonkuruEsther commented on src/components/Options.jsx
Done

2023-03-19 14:39 UTC, NiyonkuruEsther commented on src/context/AppContext.jsx
> +        answers: answers.map((item) => {
Done

2023-05-16 14:04 UTC, merged